CREATE DATABASE INVENTORY;
USE INVENTORY;
CREATE TABLE  LOGIN(ID INT, USERNAME VARCHAR(255), PASSWORD VARCHAR(255), MOBILE_NUMBER BIGINT);
CREATE TABLE  ADMINLOGIN(ID INT, USERNAME VARCHAR(255), PASSWORD VARCHAR(255), MOBILE_NUMBER BIGINT);
CREATE TABLE PRODUCT(PRODUCTID INT,PRODUCTNAME VARCHAR(255),MINSELL INT,PRICE INT, QUANTITY INT);
CREATE TABLE AGENT(PRODUCTID INT,PRODUCTNAME VARCHAR(255),TRANSACTION VARCHAR(255),QUANTITY INT,PRICE INT,TOTALCOST INT);
CREATE TABLE AGENT1(PRODUCTID INT,PRODUCTNAME VARCHAR(255),TRANSACTION VARCHAR(255),QUANTITY INT,PRICE INT,TOTALCOST INT);
INSERT INTO ADMINLOGIN(ID,USERNAME,PASSWORD,MOBILE_NUMBER)VALUES(1,"ADMIN","ADMIN",123456789);
INSERT INTO ADMINLOGIN(ID,USERNAME,PASSWORD,MOBILE_NUMBER)VALUES(2,'ADMIN1',"ADMIN1",123456780);
INSERT INTO LOGIN(ID,USERNAME,PASSWORD,MOBILE_NUMBER)VALUES(3,"AGENT","AGENT",123456781);
INSERT INTO LOGIN(ID,USERNAME,PASSWORD,MOBILE_NUMBER)VALUES(4,"AGENT1","AGENT1",123456782);
SELECT * FROM LOGIN;
SELECT * FROM ADMINLOGIN;
SELECT * FROM PRODUCT; 
SELECT * FROM AGENT;
SELECT * FROM AGENT1;
SET SQL_SAFE_UPDATES=0; 
-- DROP TABLE ADMINLOGIN;
-- DROP TABLE PRODUCT;
-- DROP TABLE AGENT;
-- DROP TABLE AGENT1;
-- DROP DATABASE INVENTORY;


